### ISSUE TITLE
Use GtkSourceView

### ISSUE THREAD

**Issue by benwaffle** [VaccineApp/vaccine#2]
once we get GtkTextView

**Comment by benwaffle** [comment]
see #14

**Comment by benwaffle** [comment]
now that we have GtkTextView, we should add this

**Comment by benwaffle** [comment]
GtkSourceView and GLib can't do language detection
maybe use a bayesian filter? https://stackoverflow.com/questions/475033/detecting-programming-language-from-a-snippet

**Comment by Prince781** [comment]
In progress in `ui-improvements` branch.

**Comment by Prince781** [comment]
Finally completed.
