### ISSUE TITLE
Filter basic NSFW content

### ISSUE THREAD

**Issue by Prince781** [VaccineApp/vaccine#21]
It would be very nice if we could hide not only 1) spoilered content and known NSFW boards (like /h/ and /gif/) but 2) unspoilered content that is NSFW.

No. 1 sounds easy and should be done first. No. 2 is just a proposal for a more advanced feature that shouldn't be tackled until we've finished other stuff.

**Comment by benwaffle** [comment]
We hide nsfw boards in the board chooser based on the setting. I've opened an issue for spoilers #51
