### ISSUE TITLE
README.md update request

### ISSUE THREAD

**Issue by plowsec** [VaccineApp/vaccine#60]
Hi !

I would love to try vaccine out. I tried to install it on my ArchLinux with yaourt -S vaccine-git, but it says no makefile has been found. Surely this is easily fixed but I'm not used to work with this kind of projects. I also tried the 3 cmds on the bottom of your README.md, but I got "no rules to build target 'run'".

Kind regards,
plowsec

**Comment by benwaffle** [comment]
The AUR package has been fixed

**Comment by plowsec** [comment]
Thanks a lot, works like a charm !
