### ISSUE TITLE
   ‍   

### ISSUE THREAD

**Issue by chris124567** [VaccineApp/vaccine#62]

**Comment by benwaffle** [comment]
Do you have gtk-plugins-bad installed?

**Comment by russianpropaganda** [comment]
Yes, I am using Gentoo and media-libs/gst-plugins-bad shows as installed.

**Comment by Prince781** [comment]
Is this with the latest version of Vaccine installed?

**Comment by Prince781** [comment]
Also, are you using a Wayland compositor?

**Comment by Prince781** [comment]
What is the output of these commands?
`gst-inspect-1.0 gtksink`
`gst-inspect-1.0 gtkglsink`

**Comment by russianpropaganda** [comment]
>Is this with the latest version of Vaccine installed?
 Cloned from git, yes.

>Also, are you using a Wayland compositor?
Nope, Xorg.

>What is the output of these commands?
[~] gst-inspect-1.0 gtksink
No such element or plugin 'gtksink'
[~] gst-inspect-1.0 gtkglsink
No such element or plugin 'gtkglsink'

**Comment by russianpropaganda** [comment]
Fixed.  I recompiled gst-plugins-bad with GTK and X use flags and now it works perfectly.  Thanks!
